<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Letgrow\\WordPress\\Core\\' => array($baseDir . '/letgrow-wordpress/core'),
    'Letgrow\\MailHistory\\' => array($baseDir . '/app'),
);
